// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCre2lbM8SEJlnb0Qhm3fQ6BtImpj8jw7s',
    appId: '1:475935779004:web:a2a896cb52f809c450c8b9',
    messagingSenderId: '475935779004',
    projectId: 'green-energy-optimization',
    authDomain: 'green-energy-optimization.firebaseapp.com',
    storageBucket: 'green-energy-optimization.firebasestorage.app',
    measurementId: 'G-DV3HY4LKCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7eU-k7x1uH2B1WVEvwOCXrZMePWRyjpI',
    appId: '1:475935779004:android:0158c901f1777d6750c8b9',
    messagingSenderId: '475935779004',
    projectId: 'green-energy-optimization',
    storageBucket: 'green-energy-optimization.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzULsJEGYfbD7k8VcyLVV77X9K8DGEztY',
    appId: '1:475935779004:ios:b8f02e8b235826f950c8b9',
    messagingSenderId: '475935779004',
    projectId: 'green-energy-optimization',
    storageBucket: 'green-energy-optimization.firebasestorage.app',
    iosBundleId: 'dev.kurodakj.greenchargeClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzULsJEGYfbD7k8VcyLVV77X9K8DGEztY',
    appId: '1:475935779004:ios:b8f02e8b235826f950c8b9',
    messagingSenderId: '475935779004',
    projectId: 'green-energy-optimization',
    storageBucket: 'green-energy-optimization.firebasestorage.app',
    iosBundleId: 'dev.kurodakj.greenchargeClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCre2lbM8SEJlnb0Qhm3fQ6BtImpj8jw7s',
    appId: '1:475935779004:web:5ddd7b6602ae1d4850c8b9',
    messagingSenderId: '475935779004',
    projectId: 'green-energy-optimization',
    authDomain: 'green-energy-optimization.firebaseapp.com',
    storageBucket: 'green-energy-optimization.firebasestorage.app',
    measurementId: 'G-PPQZE40JWP',
  );
}
